### ISSUE TITLE
Editing Orders 

### ISSUE THREAD

**Issue by jophillipsrtp** [babybunny/rebuildingtogethercaptain#361]
Hi guys,

I'm trying to edit a porta potty order for site # 17807SAB; The Porta potty order is up on ROOMs but there is only a view button and not an edit button; I need to edit the amount and fulfill it.

This is NOT urgent,

Thank You!

Jo

**Comment by caripang** [comment]
@babybunny , this is an issue of the "reconcile" function not working.
Jo - because it was placed as an order with all the details connected to the order, the process would be to fulfill the order and then reconcile it with the final cost once the invoice is received.  It looks like the fulfillment works, but the "reconcile" part when you pull up the porta potty order is what is not working.  

Luke: it currently says "Placeholder" when you try to select the order and reconcile it.

https://rebuildingtogethercaptain.appspot.com/room/help?next_key=ah9zfnJlYnVpbGRpbmd0b2dldGhlcmNhcHRhaW4taHJkchILEgpPcmRlclNoZWV0GMGsBgw

Mary talked about deleting orders and then putting them as vendor receipts when those come in, but I'm cautious about doing it that way since you then lose the original order details.  

This may be a process that should be revisited.  In the meantime, it is the "reconcile" function that is the issue.

**Comment by babybunny** [comment]
OK.  Makes sense.  I'll have to recall what the reconcile screen looked like.

**Comment by babybunny** [comment]
pushing an implementation of reconcile now. 
@caripang please check it out.   should work same as before --- go to an order list from the staff home, then it will show a link to reconcile (near the "Export CSV" button).  then you can enter actual_total.

**Comment by caripang** [comment]
Thanks, @babybunny - I tested it and it looks like it mostly works except the Vendor list will not pull up.

**Comment by babybunny** [comment]
vendor list works locally.  on prod it gives me a JS error from jeditable.  

it's probably data driven.  perhaps a value that is not escaped when it goes into the list of selections in JS. in fact I can see one of these.

**Comment by babybunny** [comment]
Ok try it now.  just pushed a fix.
